/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedApplyIdRouteImport } from './routes/_authenticated/apply.$id'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin.applications.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedApplyIdRoute = AuthenticatedApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/apply/$id': typeof AuthenticatedApplyIdRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/apply/$id': typeof AuthenticatedApplyIdRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/apply/$id': typeof AuthenticatedApplyIdRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/profile'
    | '/jobs/$id'
    | '/admin/applications'
    | '/admin/jobs'
    | '/apply/$id'
    | '/profile/edit'
    | '/admin/'
    | '/admin/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/profile'
    | '/jobs/$id'
    | '/admin/applications'
    | '/admin/jobs'
    | '/apply/$id'
    | '/profile/edit'
    | '/admin'
    | '/admin/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/jobs/$id'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/apply/$id'
    | '/_authenticated/profile/edit'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/apply/$id': {
      id: '/_authenticated/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof AuthenticatedApplyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminApplicationsRoute
    }
  }
}

interface AuthenticatedAdminApplicationsRouteChildren {
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
}

const AuthenticatedAdminApplicationsRouteChildren: AuthenticatedAdminApplicationsRouteChildren =
  {
    AuthenticatedAdminApplicationsIdRoute:
      AuthenticatedAdminApplicationsIdRoute,
  }

const AuthenticatedAdminApplicationsRouteWithChildren =
  AuthenticatedAdminApplicationsRoute._addFileChildren(
    AuthenticatedAdminApplicationsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRouteWithChildren
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApplicationsRoute:
    AuthenticatedAdminApplicationsRouteWithChildren,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedApplyIdRoute: typeof AuthenticatedApplyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedApplyIdRoute: AuthenticatedApplyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
