/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHiringRouteImport } from './routes/_authenticated/hiring'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedHiringIndexRouteImport } from './routes/_authenticated/hiring.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as JobsExternalIdRouteImport } from './routes/jobs.external.$id'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedHiringJobsRouteImport } from './routes/_authenticated/hiring.jobs'
import { Route as AuthenticatedHiringInterviewsRouteImport } from './routes/_authenticated/hiring.interviews'
import { Route as AuthenticatedHiringApplicantsRouteImport } from './routes/_authenticated/hiring.applicants'
import { Route as AuthenticatedApplyIdRouteImport } from './routes/_authenticated/apply.$id'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminImportsRouteImport } from './routes/_authenticated/admin.imports'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as ApiPublicHooksSyncJobsRouteImport } from './routes/api/public/hooks/sync-jobs'
import { Route as AuthenticatedHiringCandidatesAppIdRouteImport } from './routes/_authenticated/hiring.candidates.$appId'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin.applications.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiringRoute = AuthenticatedHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedHiringIndexRoute =
  AuthenticatedHiringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHiringRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const JobsExternalIdRoute = JobsExternalIdRouteImport.update({
  id: '/jobs/external/$id',
  path: '/jobs/external/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedHiringJobsRoute = AuthenticatedHiringJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedHiringRoute,
} as any)
const AuthenticatedHiringInterviewsRoute =
  AuthenticatedHiringInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedHiringRoute,
  } as any)
const AuthenticatedHiringApplicantsRoute =
  AuthenticatedHiringApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AuthenticatedHiringRoute,
  } as any)
const AuthenticatedApplyIdRoute = AuthenticatedApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportsRoute =
  AuthenticatedAdminImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksSyncJobsRoute = ApiPublicHooksSyncJobsRouteImport.update({
  id: '/api/public/hooks/sync-jobs',
  path: '/api/public/hooks/sync-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHiringCandidatesAppIdRoute =
  AuthenticatedHiringCandidatesAppIdRouteImport.update({
    id: '/candidates/$appId',
    path: '/candidates/$appId',
    getParentRoute: () => AuthenticatedHiringRoute,
  } as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/post-job': typeof PostJobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/hiring': typeof AuthenticatedHiringRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/apply/$id': typeof AuthenticatedApplyIdRoute
  '/hiring/applicants': typeof AuthenticatedHiringApplicantsRoute
  '/hiring/interviews': typeof AuthenticatedHiringInterviewsRoute
  '/hiring/jobs': typeof AuthenticatedHiringJobsRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/jobs/external/$id': typeof JobsExternalIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/hiring/': typeof AuthenticatedHiringIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/hiring/candidates/$appId': typeof AuthenticatedHiringCandidatesAppIdRoute
  '/api/public/hooks/sync-jobs': typeof ApiPublicHooksSyncJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/post-job': typeof PostJobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jobs/$id': typeof JobsIdRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/apply/$id': typeof AuthenticatedApplyIdRoute
  '/hiring/applicants': typeof AuthenticatedHiringApplicantsRoute
  '/hiring/interviews': typeof AuthenticatedHiringInterviewsRoute
  '/hiring/jobs': typeof AuthenticatedHiringJobsRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/jobs/external/$id': typeof JobsExternalIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/hiring': typeof AuthenticatedHiringIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/hiring/candidates/$appId': typeof AuthenticatedHiringCandidatesAppIdRoute
  '/api/public/hooks/sync-jobs': typeof ApiPublicHooksSyncJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/post-job': typeof PostJobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/hiring': typeof AuthenticatedHiringRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRouteWithChildren
  '/_authenticated/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/apply/$id': typeof AuthenticatedApplyIdRoute
  '/_authenticated/hiring/applicants': typeof AuthenticatedHiringApplicantsRoute
  '/_authenticated/hiring/interviews': typeof AuthenticatedHiringInterviewsRoute
  '/_authenticated/hiring/jobs': typeof AuthenticatedHiringJobsRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/jobs/external/$id': typeof JobsExternalIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/hiring/': typeof AuthenticatedHiringIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/_authenticated/hiring/candidates/$appId': typeof AuthenticatedHiringCandidatesAppIdRoute
  '/api/public/hooks/sync-jobs': typeof ApiPublicHooksSyncJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/post-job'
    | '/sitemap.xml'
    | '/admin'
    | '/hiring'
    | '/profile'
    | '/jobs/$id'
    | '/admin/applications'
    | '/admin/imports'
    | '/admin/jobs'
    | '/admin/submissions'
    | '/apply/$id'
    | '/hiring/applicants'
    | '/hiring/interviews'
    | '/hiring/jobs'
    | '/profile/edit'
    | '/jobs/external/$id'
    | '/admin/'
    | '/hiring/'
    | '/profile/'
    | '/admin/applications/$id'
    | '/hiring/candidates/$appId'
    | '/api/public/hooks/sync-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/post-job'
    | '/sitemap.xml'
    | '/jobs/$id'
    | '/admin/applications'
    | '/admin/imports'
    | '/admin/jobs'
    | '/admin/submissions'
    | '/apply/$id'
    | '/hiring/applicants'
    | '/hiring/interviews'
    | '/hiring/jobs'
    | '/profile/edit'
    | '/jobs/external/$id'
    | '/admin'
    | '/hiring'
    | '/profile'
    | '/admin/applications/$id'
    | '/hiring/candidates/$appId'
    | '/api/public/hooks/sync-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/post-job'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/hiring'
    | '/_authenticated/profile'
    | '/jobs/$id'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/imports'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/apply/$id'
    | '/_authenticated/hiring/applicants'
    | '/_authenticated/hiring/interviews'
    | '/_authenticated/hiring/jobs'
    | '/_authenticated/profile/edit'
    | '/jobs/external/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/hiring/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/applications/$id'
    | '/_authenticated/hiring/candidates/$appId'
    | '/api/public/hooks/sync-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PostJobRoute: typeof PostJobRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsExternalIdRoute: typeof JobsExternalIdRoute
  ApiPublicHooksSyncJobsRoute: typeof ApiPublicHooksSyncJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hiring': {
      id: '/_authenticated/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof AuthenticatedHiringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/hiring/': {
      id: '/_authenticated/hiring/'
      path: '/'
      fullPath: '/hiring/'
      preLoaderRoute: typeof AuthenticatedHiringIndexRouteImport
      parentRoute: typeof AuthenticatedHiringRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/jobs/external/$id': {
      id: '/jobs/external/$id'
      path: '/jobs/external/$id'
      fullPath: '/jobs/external/$id'
      preLoaderRoute: typeof JobsExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/hiring/jobs': {
      id: '/_authenticated/hiring/jobs'
      path: '/jobs'
      fullPath: '/hiring/jobs'
      preLoaderRoute: typeof AuthenticatedHiringJobsRouteImport
      parentRoute: typeof AuthenticatedHiringRoute
    }
    '/_authenticated/hiring/interviews': {
      id: '/_authenticated/hiring/interviews'
      path: '/interviews'
      fullPath: '/hiring/interviews'
      preLoaderRoute: typeof AuthenticatedHiringInterviewsRouteImport
      parentRoute: typeof AuthenticatedHiringRoute
    }
    '/_authenticated/hiring/applicants': {
      id: '/_authenticated/hiring/applicants'
      path: '/applicants'
      fullPath: '/hiring/applicants'
      preLoaderRoute: typeof AuthenticatedHiringApplicantsRouteImport
      parentRoute: typeof AuthenticatedHiringRoute
    }
    '/_authenticated/apply/$id': {
      id: '/_authenticated/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof AuthenticatedApplyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imports': {
      id: '/_authenticated/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthenticatedAdminImportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/sync-jobs': {
      id: '/api/public/hooks/sync-jobs'
      path: '/api/public/hooks/sync-jobs'
      fullPath: '/api/public/hooks/sync-jobs'
      preLoaderRoute: typeof ApiPublicHooksSyncJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hiring/candidates/$appId': {
      id: '/_authenticated/hiring/candidates/$appId'
      path: '/candidates/$appId'
      fullPath: '/hiring/candidates/$appId'
      preLoaderRoute: typeof AuthenticatedHiringCandidatesAppIdRouteImport
      parentRoute: typeof AuthenticatedHiringRoute
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminApplicationsRoute
    }
  }
}

interface AuthenticatedAdminApplicationsRouteChildren {
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
}

const AuthenticatedAdminApplicationsRouteChildren: AuthenticatedAdminApplicationsRouteChildren =
  {
    AuthenticatedAdminApplicationsIdRoute:
      AuthenticatedAdminApplicationsIdRoute,
  }

const AuthenticatedAdminApplicationsRouteWithChildren =
  AuthenticatedAdminApplicationsRoute._addFileChildren(
    AuthenticatedAdminApplicationsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRouteWithChildren
  AuthenticatedAdminImportsRoute: typeof AuthenticatedAdminImportsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApplicationsRoute:
    AuthenticatedAdminApplicationsRouteWithChildren,
  AuthenticatedAdminImportsRoute: AuthenticatedAdminImportsRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedHiringRouteChildren {
  AuthenticatedHiringApplicantsRoute: typeof AuthenticatedHiringApplicantsRoute
  AuthenticatedHiringInterviewsRoute: typeof AuthenticatedHiringInterviewsRoute
  AuthenticatedHiringJobsRoute: typeof AuthenticatedHiringJobsRoute
  AuthenticatedHiringIndexRoute: typeof AuthenticatedHiringIndexRoute
  AuthenticatedHiringCandidatesAppIdRoute: typeof AuthenticatedHiringCandidatesAppIdRoute
}

const AuthenticatedHiringRouteChildren: AuthenticatedHiringRouteChildren = {
  AuthenticatedHiringApplicantsRoute: AuthenticatedHiringApplicantsRoute,
  AuthenticatedHiringInterviewsRoute: AuthenticatedHiringInterviewsRoute,
  AuthenticatedHiringJobsRoute: AuthenticatedHiringJobsRoute,
  AuthenticatedHiringIndexRoute: AuthenticatedHiringIndexRoute,
  AuthenticatedHiringCandidatesAppIdRoute:
    AuthenticatedHiringCandidatesAppIdRoute,
}

const AuthenticatedHiringRouteWithChildren =
  AuthenticatedHiringRoute._addFileChildren(AuthenticatedHiringRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHiringRoute: typeof AuthenticatedHiringRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedApplyIdRoute: typeof AuthenticatedApplyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHiringRoute: AuthenticatedHiringRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedApplyIdRoute: AuthenticatedApplyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PostJobRoute: PostJobRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JobsIdRoute: JobsIdRoute,
  JobsExternalIdRoute: JobsExternalIdRoute,
  ApiPublicHooksSyncJobsRoute: ApiPublicHooksSyncJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
